{
 "title": "Kubernetes Overview",
 "description": "Assorted metrics for an overview of your cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Step", "query": "30s,1m,5m,15m,1h" },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_pod_container_info)" }
   ]
  },
  {
   "title": "Kubernetes Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "kubernetes_build_info", "legendFormat": "{{ git_version }}" }
   ]
  },
  {
   "title": "Container Runtime Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, kube_node_info)",
     "legendFormat": "{{ container_runtime_version }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(etcd_server_version)" }
   ]
  },
  {
   "title": "Abnormal Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{phase!~\"Running|Succeeded\"} == 1) OR ON(namespace, pod) (kube_pod_status_ready{condition=\"true\"} == 0)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running != 1) OR vector(0)"
    }
   ]
  },
  {
   "title": "ETCD Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "etcd_server_version", "legendFormat": "{{ server_version }}" }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(1, kubernetes_build_info)", "legendFormat": "{{ platform }}" }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_node_status_condition{condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Leaderless ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(etcd_server_has_leader == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "APIServer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "APIServer Requests",
   "type": "graph",
   "description": "The number of requests handled by kube-apiserver per second, excluding CONNECT, WATCH, and WATCHLIST",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_total{resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[5m])",
     "legendFormat": "{{ verb }} {{ resource }}.{{ group }}"
    },
    {
     "expr": "rate(apiserver_request_total{resource!=\"\", group=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[5m])",
     "legendFormat": "{{ verb }} {{ resource }}"
    }
   ]
  },
  {
   "title": "Slow APIServer Requests",
   "type": "graph",
   "description": "The number of requests per second that have taken kube-apiserver more than 3 seconds to handle, excluding CONNECT, WATCH, and WATCHLIST",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_duration_seconds_bucket{resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", le=\"+Inf\"}[5m])\n  - IGNORING(le) rate(apiserver_request_duration_seconds_bucket{le=\"3\"}[5m])",
     "legendFormat": "{{ verb }} {{ resource }}.{{ group }}"
    },
    {
     "expr": "rate(apiserver_request_duration_seconds_bucket{resource!=\"\", group=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", le=\"+Inf\"}[5m])\n  - IGNORING(le) rate(apiserver_request_duration_seconds_bucket{le=\"3\"}[5m])",
     "legendFormat": "{{ verb }} {{ resource }}"
    }
   ]
  },
  {
   "title": "Failed APIServer Requests",
   "type": "graph",
   "description": "The number of requests per second that were handled by kube-apiserver and returned 4xx or 5xx, excluding CONNECT, WATCH, and WATCHLIST",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_total{resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(4|5)\\\\d{2}\"}[5m])",
     "legendFormat": "{{ verb }} {{ resource }}.{{ group }} {{ code }}"
    },
    {
     "expr": "rate(apiserver_request_total{resource!=\"\", group=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(4|5)\\\\d{2}\"}[5m])",
     "legendFormat": "{{ verb }} {{ resource }} {{ code }}"
    }
   ]
  },
  {
   "title": "APIServer Response Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_response_sizes_sum[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "APIServer Watch Events Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_watch_events_sizes_sum[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "APIServer Watch Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_watch_events_total{group!=\"\"}[5m])) by (group, version, kind)",
     "legendFormat": "{{ group }}/{{ version }}.{{ kind }}"
    },
    {
     "expr": "sum(rate(apiserver_watch_events_total{group=\"\"}[5m])) by (version, kind)",
     "legendFormat": "{{ version }}.{{ kind }}"
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ETCD Leader Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_join(etcd_server_has_leader, \"etcd_key\", \"/\", \"instance\", \"job\")"
    },
    {
     "expr": "label_join(etcd_server_is_leader, \"etcd_key\", \"/\", \"instance\", \"job\")"
    }
   ]
  },
  {
   "title": "ETCD WAL Fsync Latency - P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m]))",
     "legendFormat": "{{ job }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD Committed Proposals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total[5m])",
     "legendFormat": "{{ job }} - {{ instance}}"
    }
   ]
  },
  {
   "title": "ETCD Leader Change Observed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "per hour" }
   ],
   "targets": [
    {
     "expr": "increase(etcd_server_leader_changes_seen_total[1h])",
     "legendFormat": "{{ job }} - {{ instance}}"
    }
   ]
  },
  {
   "title": "ETCD Commit to Disk Latency - P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket[5m]))",
     "legendFormat": "{{ job }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD Failed Proposals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_failed_total[5m])",
     "legendFormat": "{{ job }} - {{ instance}}"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU Saturation - Top 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_cpu_usage_seconds_total{pod!=\"\", container!=\"\"}[5m]) / ON(namespace, pod, container) GROUP_LEFT max(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\"}) without (node))",
     "legendFormat": "{{ namespace }}/{{ pod }}: {{ container }}"
    }
   ]
  },
  {
   "title": "Container Memory Saturation - Top 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, container_memory_working_set_bytes{pod!=\"\", container!=\"\"} / ON(namespace, node, pod, container) GROUP_LEFT max(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"}) without (node))",
     "legendFormat": "{{ namespace }}/{{ pod }}: {{ container }}"
    }
   ]
  },
  {
   "title": "PVC Space Saturation - Top 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Node CPU Saturation - Top 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load5 / count(max(node_cpu_seconds_total) without (mode)) without (cpu)",
     "legendFormat": "{{ node }}"
    },
    { "expr": "vector(1)", "legendFormat": "reference" }
   ]
  },
  {
   "title": "Node Memory Saturation - Top 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, 1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Filesystem Space Saturation - Top 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{fstype!=\"tmpfs\"} / node_filesystem_size_bytes",
     "legendFormat": "{{ node }}: {{ device }}"
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workqueue Work Duration - P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (job, name, le))",
     "legendFormat": "{{ job }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Non-empty Workqueues",
   "type": "graph",
   "description": "The number of items in a Workqueue that are waiting to be processed. This includes Workqueues from any components.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth) by (job, name)",
     "legendFormat": "{{ job }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Workqueue Retried Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total[5m])) by (job, name)",
     "legendFormat": "{{ job }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Kubelet Runtime OP Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "increase(kubelet_runtime_operations_errors_total[1m])",
     "legendFormat": "{{ operation_type }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Unavailable APIServices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(aggregator_unavailable_apiservice) by (name)) == 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Failed Monitoring Targets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up == 0", "legendFormat": "{{ job }} - {{ instance }}" }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" },
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Core Throttled by instance",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total pods" }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Global Network Utilization by device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*\"}[$__rate_interval])) by (device)",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*\"}[$__rate_interval]))  by (device)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total[$__rate_interval]))",
     "legendFormat": "Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total[$__rate_interval]))",
     "legendFormat": "Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__rate_interval])) by (namespace)",
     "legendFormat": "Received : {{ namespace }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$__rate_interval])) by (namespace)",
     "legendFormat": "Transmitted : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Total Network Received (with all virtual devices) by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (without loopback)  by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*|lo\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*|lo\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (loopback only) by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  }
 ]
}